source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.0'

# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'

# Use Puma as the app server
gem 'puma', '~> 4.3'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# serializers
gem 'active_model_serializers'

# AMQP ruby client
gem 'bunny'

# api doc
gem 'apipie-rails'

# logs
gem 'lograge'
gem 'remote_syslog_logger'

# monitoring
gem 'newrelic_rpm'

# Use Json Web Token (JWT) for token based authentication
gem 'jwt'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# lint
gem 'rubocop'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# authorization
gem 'pundit'

# background job
gem 'sidekiq'

# rabbitmq client
gem 'rabbitmq_pub_sub', git: 'https://github.com/edimossilva/rabbitmq_pub_sub'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-remote'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'factory_bot_rails'
  gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'master'
  gem 'rspec-rails', '~> 4.0.0.beta'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'simplecov-console'
end
