FROM ruby:alpine3.11

RUN gem install bundler
RUN gem install shotgun

WORKDIR /app

COPY ./volume/api-gateway/Gemfile /app/Gemfile
COPY ./volume/api-gateway/Gemfile.lock /app/Gemfile.lock

RUN bundle install

CMD shotgun config.ru -o 0.0.0.0
