# base image
FROM edimossilva/node-angular-cypress:web_client

# install and cache app dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install


# add app
COPY . /app

# start app
CMD ng serve
