# base image
FROM node

RUN apt-get update --yes
RUN apt-get install --yes libgtk2.0-0 libgtk-3-0 libnotify-dev libnotify4 libgconf2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb


# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN npm install cypress --save-dev

# install and cache app dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

# add app
COPY . /app


# start app
CMD ng serve
