user1 = User.create(username: 'registered_user1', password: '111', access_level: User.access_levels[:registred])
User.create(username: 'registered_user2', password: '222', access_level: User.access_levels[:registred])
User.create(username: 'admin_user1', password: '111', access_level: User.access_levels[:admin])
User.create(username: 'admin_user2', password: '222', access_level: User.access_levels[:admin])
User.create(username: 'test_user', password: '111', access_level: User.access_levels[:admin])
TaskList.create(name: 'task1', frequence_type: TaskList.frequence_types[:daily], user_id: user1.id)

User.create(username: 'thomas', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'alan', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'jhonatta', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'josmadelmo', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'ramon', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'neylanio', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'thiago', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'emmanuel', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'david', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'iury', password: '123456', access_level: User.access_levels[:admin])
User.create(username: 'roanderson', password: '123456', access_level: User.access_levels[:admin])
