user1 = User.create(username: 'registered_user1', password: '111', access_level: User.access_levels[:registred])
User.create(username: 'registered_user2', password: '222', access_level: User.access_levels[:registred])
User.create(username: 'admin_user1', password: '111', access_level: User.access_levels[:admin])
User.create(username: 'admin_user2', password: '222', access_level: User.access_levels[:admin])
User.create(username: 'test_user', password: '111', access_level: User.access_levels[:admin])
TaskList.create(name: 'task1', frequence_type: TaskList.frequence_types[:daily], user_id: user1.id)
