FROM ruby:alpine3.11

RUN gem install bundler
RUN gem install shotgun

WORKDIR /app

COPY ./Gemfile /app/Gemfile
COPY ./Gemfile.lock /app/Gemfile.lock

RUN bundle install

CMD shotgun config.ru -o 0.0.0.0
