source 'https://rubygems.org'

gem 'bunny'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activesupport'
gem 'pry'
gem 'pry-nav'
gem 'pry-remote'
gem 'rabbitmq_pub_sub', git: 'https://github.com/edimossilva/rabbitmq_pub_sub'
gem 'redis'
gem 'require_all'

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov'
  gem 'simplecov-console'
end
